### ISSUE TITLE
Mobile Chrome can't select dropdown

### ISSUE THREAD

**Issue by prurigro** [Formstone/Formstone#192]
This is both the case on mobile as well as with the chrome dev tools responsive mode. Formstone `0.8.x` used to pop up with the built-in select viewer, but it now does nothing when a dropdown is selected.

This is both the case on personal projects using `1.2.1` as well as all the demos here: https://formstone.it/components/dropdown/demo/

Cheers!

**Comment by prurigro** [comment]
Actually scratch that, I just downgraded and get the same behaviour so it might be something that changed in chrome/mobile chrome...

**Comment by benplum** [comment]
I'm seeing the browser defaults in Chrome mobile and responsive view.

![screen shot 2016-09-16 at 4 55 34 pm](https://cloud.githubusercontent.com/assets/1130075/18600989/7227fcc2-7c2e-11e6-9dd2-2812cbdd282c.png)

**Comment by prurigro** [comment]
What version of chrome are you testing on? I'm running version 53.0.2785.101 here.

That said, I was able to get the select to work the way it used to on my phone by bumping up the z-index of the select on mobile.

Edit: I've never had mobile chrome show dropdowns like you have in your screenshot.

**Comment by benplum** [comment]
Looks like I'm on 52.0.2743.116. Hmm, I'll do some digging into why z-index would have an effect. 

Edit: I just updated to the same version as you and am seeing the bug, hopefully we can push a release soon.

**Comment by prurigro** [comment]
It's not that z-index fixes the issue if the intended behaviour is to have the dropdown appear like it does on other devices. Setting `select: z-index: 3;` and `.fs-dropdown-options { display: none; }` makes it override the formstone with how selects are handled natively, so it's more like a hack than a fix. I'm a bit short on time today, but I might give it a closer look if the issue is still open next week.

Thanks for taking a look!

**Comment by rgracia** [comment]
Safari on iOS is affected as well BTW. Not just Chrome. We have also confirmed this on the latest Android OS.

**Comment by pcross1986** [comment]
Holy hell please fix and if you can please provide what the fix is or what the problem is. This is a nightmare...

**Comment by benplum** [comment]
Looks like browsers are [no longer allowing a select to be programmatically](http://stackoverflow.com/a/39635285/2612062) opened (since it's an 'untrusted event'). This is probably for the good of the user, but means the script is broken on mobile. @prurigro's solution is good fix, since pushing the select above the handle will force the user to trigger the select. 

We may need to ultimately fallback to opening the replacement options instead of the native select on mobile, but I'm open to suggestions.

**Comment by pcross1986** [comment]
Any chance you or @prurigro could check something for me? I tried using @prurigro 's technique, but I am getting no luck. This is extremely frustrating because this is the only thing holding me back on a project.

http://rpn.revampdm.com/
the Search form or any select boxes.
Looks to be using Selecter 3.2.3
Testing on Samsung Galaxy S7 edge (Android OS), Google Chrome v 53+

I am using the following CSS code:

`@media screen and (max-width: 39.9375em) {
  .selecter-element {
    z-index: 3 !important;
  }

  .selecter-options { display: none !important; }
}`

Any help would be greatly appreciated.

**Comment by benplum** [comment]
The selects are opening the native controls for me.

**Comment by pcross1986** [comment]
Wow, not for me. What device are you using? What version of Chrome? I am Samsung Galaxy S7 Edge. Here is my screenshot of version. But when I try clicking on selects, nothing happens at all. No flash or anything.

UPDATE: To note, the native DOES open on my laptop computer, Chrome browser EMULATOR within the dev tools, but on my ACTUAL device, nothing happens.

![screenshot_20160929-093801](https://cloud.githubusercontent.com/assets/16227415/18958874/d435002c-8629-11e6-809e-a607b7f89bb0.png)

**Comment by benplum** [comment]
Looks like the same version: 

![screenshot_20160929-110448](https://cloud.githubusercontent.com/assets/1130075/18959653/f97d96d6-8634-11e6-8353-85ea1c38fafa.png)

![screenshot_20160929-110427](https://cloud.githubusercontent.com/assets/1130075/18959654/facd3d16-8634-11e6-97fa-fec52ef0a0eb.png)

**Comment by pcross1986** [comment]
**UPDATE**

Hope you guys dont mind all these updates lol. I figured they are important for other users in case they run into similar problems. So next I thought of, "Hmmm maybe uninstall Chrome from my phone and reinstall?" So I uninstalled Chrome, however it seemed to uninstall version 53... and back to version 50. I checked the site and of course the native works fine. But then I was like, "Well, but many people automatically update their chrome browser, therefore would have version 53. Well, I went back to Playstore and searched Chrome and hit the Update button as version 50 was currently installed. Once update was complete, I reopened Chrome and refreshed page, and BAM! the native is working. I also checked version after testing and looks to be version 53. Weird experience.....

**Comment by benplum** [comment]
That's pretty strange - perhaps it was a caching issue on your device? Anyway, I'm hoping to get an update with the z-index fix out as soon as I have a chance.

**Comment by pcross1986** [comment]
Really appreciate your help and patience!

**Comment by benplum** [comment]
No worries - good luck with the launch!

**Comment by rgracia** [comment]
So we increased the z-index of the select list itself and it now serves the default behavior for mobile on our site. The initial look of the Formstone widget is still visible, which works for us. However, we have used Select2 in some of our older projects and later switched to Formstone for subsequent ones and I am seeing that Select2 widgets still work in the same browser versions that Formstone doesn't so is this really a case of browsers no longer allowing a select to be programmatically opened or something else? Isn't Select2 essentially doing the a similar thing?

**Comment by benplum** [comment]
Select 2 doesn't trigger the native browser UI on mobile, it should still draw the custom replacement. Formstone Select would open the native UI on mobile programmatically. Moving forward we have two options:
- Always display the plugin replacement markup and never use the browser UI on mobile.
- Increase the z-index on mobile to force the actual select to be triggered when a user taps on a handle (the fix mentioned in this thread).

Option 1 might be the best simply because it will always be predictable, there's no telling how browsers may change security practices in the future (for example, they may make select elements with `opacity: 0` non-clickable).

**Comment by rgracia** [comment]
Makes sense @benplum. Thanks for the clarification. As for what option would be best going forward, I am on the camp to let the OS handle select lists on Mobile devices, but the rest of the dev community here may be on your side for Option 1. As long as we can override option 1 with option 2 with CSS once this is updated, it should be good for everyone. We started asking our designers to stop styling select lists a while back for the same reason, but it is good to have options.

**Comment by benplum** [comment]
I'm sure we can keep both and make it some sort of option, similar to how a developer can force the `mobile` version of the Lightbox on desktop devices.

**Comment by timbouchard** [comment]
Just ran into this bug today. Is the z-index hack the way to go for now? Any idea on when a patch may get pushed for this bug?

I've got about 50ish older sites using dropdown :(

**Comment by benplum** [comment]
Fixed in 1.2.2. The plugin will now default to using the custom options element on mobile devices. Developers can still opt to use the native browser controls by setting the `mobile: true` option at initialization. The `z-index` of the `fs-dropdown-element` will need to be higher then the `z-index`of the `fs-dropdown-selected` element (unless it's `multiple`): https://github.com/Formstone/Formstone/blob/master/src/less/dropdown.less#L120-L126

**Comment by felicianuniversity** [comment]
Hello,
 I am having the same issues,  Apologies for being a newbie to this.  I download the latest version after purchase, uploaded it and it still does not work on any mobile devices.   Is there something I am missing?  Thanks in Advance!

**Comment by benplum** [comment]
What version are you using? Make sure you grab the latest release from GitHub: https://github.com/Formstone/Formstone/releases

You can also use npm to install and update: https://www.npmjs.com/package/formstone

**Comment by felicianuniversity** [comment]
Thanks for the quick get back!

I am using the one that is available after purchase from your site.

Formstone<https://www.uplabs.com/posts/formstone>

commercial License | Order #6195
Is this the correct one?

Best,
Edwin-

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by benplum** [comment]
Always use the latest release from GitHub: https://github.com/Formstone/Formstone/releases UpLabs may be behind.
