### ISSUE TITLE
Navigation Closing

### ISSUE THREAD

**Issue by benplum** [Formstone/Formstone#29]
When the menu button exists inside the page content, the close button fires twice which reopens the menu. 

Remove pointer events?
Check target and kill event?

**Comment by benplum** [comment]
Also fixed in 0.6.7 - had to do with removing namespaced events.

**Comment by smartpill** [comment]
I'm using the latest version (0.7.15) and I'm still having that issue in iOS 8.4 here (see top right corner):

http://smartpilldesign.com/dev/nhi
